In [4]:
import numpy as n 
n.array(type([10,20,30,40,50]))

array(<class 'list'>, dtype=object)

In [8]:
import numpy as n 
n.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
import numpy as n 
aee=n.array([7,8,9],dtype=float)
print(type(aee))

<class 'numpy.ndarray'>

In [18]:
import numpy as n 
arr1=n.zeros(6)
arr2=n.zeros((3,2),dtype=int)
print(arr1,arr2)

[0. 0. 0. 0. 0. 0.] [[0 0]
 [0 0]
 [0 0]]

In [19]:
import numpy as np 
np.empty((2,2))  //it gives garbage values and empty allocates free space so prefered over zeros and  the garbage values will be there before in zeros it is replaced so it is faster

array([[2.12199579e-314, 1.09919382e-311],
       [6.22522714e-321, 1.09919382e-311]])

In [23]:
import numpy as n 
n.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [26]:
import numpy as n 
n.linspace(0,1,6)  //in inspace the 1 is inclusive but not in arange it is inclusive

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [28]:
import numpy as n 
n.random.random((3,3))

array([[0.7936571 , 0.90941421, 0.41518147],
       [0.89725201, 0.7680489 , 0.27030422],
       [0.88883154, 0.08941892, 0.12925151]])

In [3]:
import numpy as np
arr = np.arange(1, 21).reshape(4, 5)
print("Array:\n", arr)
print("Number of dimensions :", arr.ndim)
print("Shape :", arr.shape)
print("Size :", arr.size)
print("Data type :", arr.dtype)

Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Number of dimensions : 2
Shape : (4, 5)
Size : 20
Data type : int32

In [17]:
import numpy as n
x=n.arange(50)
print(x)
print(x.size)
print(x.nbytes)
np.random.seed(0)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
50
200

In [41]:
import numpy as np
arr=np.arange(1,13).reshape(3,4)
print(arr)
print(arr[2,3])
print(arr[:,3])
print(arr[2,:])
a=arr[-1,:].reshape((4,1))
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
[ 4  8 12]
[ 9 10 11 12]
[[ 9]
 [10]
 [11]
 [12]]

In [39]:
import numpy as np
x=np.arange(12).reshape((3,4))
print(x)
row=np.vsplit(x,[2])
col=np.hsplit(x,[2])
print(row)
print(col)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [5]:
titanic = sns.load_dataset('titanic')
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [7]:
titanic.pivot_table('survived', index='sex', columns='class')

C:\Users\monal\AppData\Local\Temp\ipykernel_3316\1756680182.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table('survived', index='sex', columns='class')

class      First    Second     Third
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [9]:
age = pd.cut(titanic['age'], [0, 18, 80])

titanic.pivot_table(
    values='survived',
    index=['sex', age],
    columns='class'
)

C:\Users\monal\AppData\Local\Temp\ipykernel_3316\2476363581.py:3: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table(

class               First    Second     Third
sex    age
female (0, 18]   0.909091  1.000000  0.511628
       (18, 80]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 80]  0.375000  0.071429  0.133663

In [13]:
titanic.pivot_table('survived',index='sex',columns=['class','alone'])

C:\Users\monal\AppData\Local\Temp\ipykernel_3316\3527023207.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table('survived',index='sex',columns=['class','alone'])

class      First              Second               Third
alone      False     True      False     True      False     True
sex
female  0.966667  0.970588  0.931818  0.906250  0.416667  0.616667
male    0.425532  0.333333  0.277778  0.097222  0.180723  0.121212

In [19]:
titanic.pivot_table(index='sex',columns='class',aggfunc={'survived':sum,'fare':'mean'})

C:\Users\monal\AppData\Local\Temp\ipykernel_3316\3324049244.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table(index='sex',columns='class',aggfunc={'survived':sum,'fare':'mean'})
C:\Users\monal\AppData\Local\Temp\ipykernel_3316\3324049244.py:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  titanic.pivot_table(index='sex',columns='class',aggfunc={'survived':sum,'fare':'mean'})

              fare                       survived
class        First     Second      Third    First Second Third
sex
female  106.125798  21.970121  16.118810       91     70    72
male     67.226127  19.741782  12.661633       45     17    47

In [21]:
titanic.pivot_table(index='sex',columns='class',aggfunc={'age':'min','fare':'min'})

C:\Users\monal\AppData\Local\Temp\ipykernel_3316\1226989719.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table(index='sex',columns='class',aggfunc={'age':'min','fare':'min'})

         age                  fare
class  First Second Third    First Second Third
sex
female  2.00   2.00  0.75  25.9292   10.5  6.75
male    0.92   0.67  0.42   0.0000    0.0  0.00

In [23]:
data = {
    "department": [
        "CSE",
        "AIML",
        "ECE",
        "CSE",
        "ECE",
        "AIML",
        "CSE",
        "ECE",
        "AIML",
        "CSE",
        "AIML",
        "ECE",
    ],
    "gender": ["M", "F", "F", "F", "M", "M", "M", "F", "M", "F", "M", "M"],
    "salary": [
        85000,
        92000,
        78000,
        90000,
        76000,
        95000,
        82000,
        80000,
        88000,
        91000,
        97000,
        75000,
    ],
}

df = pd.DataFrame(data)
print(df)

   department gender  salary
0         CSE      M   85000
1        AIML      F   92000
2         ECE      F   78000
3         CSE      F   90000
4         ECE      M   76000
5        AIML      M   95000
6         CSE      M   82000
7         ECE      F   80000
8        AIML      M   88000
9         CSE      F   91000
10       AIML      M   97000
11        ECE      M   75000

In [ ]:
titanic.pivot_table